# Generated by Django 2.2.2 on 2019-06-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_majorcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='name',
        ),
        migrations.AddField(
            model_name='major',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='students.MajorCategory'),
            preserve_default=False,
        ),
    ]
