# Generated by Django 2.2.2 on 2019-06-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20190620_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorcategory',
            name='child',
        ),
    ]
